# Generated by Django 5.2.4 on 2025-08-07 06:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmrSyncStatus",
            fields=[
                (
                    "sync_id",
                    models.CharField(
                        default=uuid.uuid4,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("patient_emr_id", models.CharField(max_length=100)),
                ("last_sync_time", models.DateTimeField()),
                ("sync_success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("retry_count", models.IntegerField(default=0)),
                (
                    "emr_raw_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "emr_department",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("emr_appointment_date", models.DateField(blank=True, null=True)),
                ("emr_appointment_time", models.TimeField(blank=True, null=True)),
                (
                    "emr_doctor_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "emr_room_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "mapped_state",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("UNREGISTERED", "Unregistered"),
                            ("ARRIVED", "Arrived"),
                            ("REGISTERED", "Registered"),
                            ("WAITING", "Waiting"),
                            ("CALLED", "Called"),
                            ("ONGOING", "Ongoing"),
                            ("COMPLETED", "Completed"),
                            ("PAYMENT", "Payment"),
                            ("FINISHED", "Finished"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "mapping_rules_version",
                    models.CharField(default="1.0", max_length=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emr_sync_statuses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "emr_sync_status",
                "ordering": ["-last_sync_time"],
                "indexes": [
                    models.Index(
                        fields=["patient_emr_id"], name="emr_sync_st_patient_660dd7_idx"
                    ),
                    models.Index(
                        fields=["last_sync_time"], name="emr_sync_st_last_sy_c8ef0b_idx"
                    ),
                    models.Index(
                        fields=["mapped_state"], name="emr_sync_st_mapped__c614b8_idx"
                    ),
                ],
            },
        ),
    ]
