# Generated by Django 5.2.4 on 2025-09-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PredictionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("department", models.CharField(max_length=100)),
                ("current_wait_time", models.FloatField()),
                ("predicted_wait_time", models.FloatField()),
                ("actual_wait_time", models.FloatField(blank=True, null=True)),
                ("congestion_level", models.FloatField()),
                ("model_version", models.CharField(max_length=20)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["timestamp", "department"],
                        name="integration_timesta_6091b5_idx",
                    )
                ],
            },
        ),
    ]
