# Generated by Django 5.2.4 on 2025-10-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0002_predictionlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emrsyncstatus",
            name="mapped_state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("UNREGISTERED", "Unregistered"),
                    ("ARRIVED", "Arrived"),
                    ("REGISTERED", "Registered"),
                    ("WAITING", "Waiting"),
                    ("CALLED", "Called"),
                    ("IN_PROGRESS", "In Progress"),
                    ("PAYMENT", "Payment"),
                    ("FINISHED", "Finished"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
