# Generated by Django 5.2.4 on 2025-08-09 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_dashboard", "0001_initial"),
        ("authentication", "0002_remove_user_pw_hash"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationSettings",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="notification_settings",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
                (
                    "queue_update",
                    models.BooleanField(default=True, verbose_name="대기열 업데이트 알림"),
                ),
                (
                    "patient_call",
                    models.BooleanField(default=True, verbose_name="환자 호출 알림"),
                ),
                (
                    "exam_ready",
                    models.BooleanField(default=True, verbose_name="검사 준비 알림"),
                ),
                (
                    "exam_complete",
                    models.BooleanField(default=True, verbose_name="검사 완료 알림"),
                ),
                (
                    "appointment_reminder",
                    models.BooleanField(default=True, verbose_name="예약 알림"),
                ),
                ("system", models.BooleanField(default=True, verbose_name="시스템 알림")),
                (
                    "emergency",
                    models.BooleanField(default=True, verbose_name="긴급 알림 (항상 활성화 권장)"),
                ),
                (
                    "do_not_disturb_enabled",
                    models.BooleanField(default=False, verbose_name="방해금지 모드 활성화"),
                ),
                (
                    "do_not_disturb_start",
                    models.TimeField(blank=True, null=True, verbose_name="방해금지 시작 시간"),
                ),
                (
                    "do_not_disturb_end",
                    models.TimeField(blank=True, null=True, verbose_name="방해금지 종료 시간"),
                ),
                (
                    "notification_sound",
                    models.CharField(
                        choices=[
                            ("default", "기본음"),
                            ("vibrate", "진동만"),
                            ("silent", "무음"),
                        ],
                        default="default",
                        max_length=20,
                        verbose_name="알림 소리",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "알림 설정",
                "verbose_name_plural": "알림 설정 목록",
                "db_table": "notification_settings",
            },
        ),
    ]
