# Generated by Django 4.2.7 on 2025-07-19 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='예약 ID')),
                ('status', models.CharField(choices=[('waiting', '대기중'), ('ongoing', '진행중'), ('done', '완료'), ('delayed', '지연')], default='waiting', max_length=10, verbose_name='상태')),
                ('arrival_confirmed', models.BooleanField(default=False, verbose_name='도착 확인')),
                ('scheduled_at', models.DateTimeField(verbose_name='예약 시간')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
            ],
            options={
                'verbose_name': '검사 예약',
                'verbose_name_plural': '검사 예약 목록',
                'db_table': 'appointments',
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False, verbose_name='이력 ID')),
                ('action', models.CharField(choices=[('created', '예약 생성'), ('confirmed', '도착 확인'), ('status_changed', '상태 변경'), ('time_changed', '시간 변경'), ('cancelled', '예약 취소')], max_length=20, verbose_name='액션')),
                ('note', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
            ],
            options={
                'verbose_name': '예약 변경 이력',
                'verbose_name_plural': '예약 변경 이력 목록',
                'db_table': 'appointment_histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('exam_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='검사 ID')),
                ('title', models.CharField(help_text='예: 흉부 X-ray, 복부 CT, 뇌 MRI', max_length=200, verbose_name='검사명')),
                ('description', models.TextField(help_text='검사 상세 설명', verbose_name='검사 설명')),
                ('department', models.CharField(help_text='예: 영상의학과, 진단검사의학과', max_length=100, verbose_name='담당 부서')),
                ('duration', models.IntegerField(help_text='분 단위', verbose_name='예상 소요 시간')),
                ('is_active', models.BooleanField(default=True, help_text='검사 시행 가능한 검사 여부', verbose_name='활성 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '검사',
                'verbose_name_plural': '검사 목록',
                'db_table': 'exams',
                'ordering': ['department', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ExamPreparation',
            fields=[
                ('prep_id', models.AutoField(primary_key=True, serialize=False, verbose_name='준비사항 ID')),
                ('title', models.CharField(help_text='예: 8시간 금식, 방광 충만 상태 유지', max_length=200, verbose_name='준비 사항')),
                ('description', models.TextField(verbose_name='상세 설명')),
                ('is_required', models.BooleanField(default=True, verbose_name='필수 여부')),
                ('exam', models.ForeignKey(db_column='exam_id', on_delete=django.db.models.deletion.CASCADE, related_name='preparations', to='appointments.exam', verbose_name='검사')),
            ],
            options={
                'verbose_name': '검사 준비사항',
                'verbose_name_plural': '검사 준비사항 목록',
                'db_table': 'exam_preparations',
                'ordering': ['exam', '-is_required', 'title'],
            },
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['department'], name='exams_departm_022a01_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['is_active'], name='exams_is_acti_5cee66_idx'),
        ),
        migrations.AddField(
            model_name='appointmenthistory',
            name='appointment',
            field=models.ForeignKey(db_column='appointment_id', on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='appointments.appointment', verbose_name='예약'),
        ),
        migrations.AddField(
            model_name='appointmenthistory',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_changes', to=settings.AUTH_USER_MODEL, verbose_name='변경자'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='exam',
            field=models.ForeignKey(db_column='exam_id', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='appointments.exam', verbose_name='검사'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='환자'),
        ),
        migrations.AddIndex(
            model_name='exampreparation',
            index=models.Index(fields=['exam', 'is_required'], name='exam_prepar_exam_id_17dab8_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmenthistory',
            index=models.Index(fields=['appointment', 'created_at'], name='appointment_appoint_08501f_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmenthistory',
            index=models.Index(fields=['action'], name='appointment_action_7efe73_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['user', 'scheduled_at'], name='appointment_user_id_ed0db4_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['exam', 'scheduled_at'], name='appointment_exam_id_8a2787_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status', 'scheduled_at'], name='appointment_status_e303fa_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['scheduled_at'], name='appointment_schedul_2da7be_idx'),
        ),
    ]
