# Generated by Django 5.2.4 on 2025-07-24 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampreparation',
            name='icon',
            field=models.CharField(blank=True, help_text='준비사항을 나타내는 아이콘 이미지 (예: URL 또는 파일 경로)', max_length=200, null=True, verbose_name='아이콘 이미지'),
        ),
    ]
