# Generated by Django 5.2.4 on 2025-07-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_exampreparation_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='building',
            field=models.CharField(blank=True, help_text='검사가 진행되는 건물명 (예: 본관, 별관)', max_length=100, null=True, verbose_name='건물명'),
        ),
        migrations.AddField(
            model_name='exam',
            name='category',
            field=models.CharField(blank=True, help_text='예: "imaging", "blood", "urine", "cardiac"', max_length=100, null=True, verbose_name='검사 분류'),
        ),
        migrations.AddField(
            model_name='exam',
            name='floor',
            field=models.CharField(blank=True, help_text='검사가 진행되는 층수', max_length=50, null=True, verbose_name='층수'),
        ),
        migrations.AddField(
            model_name='exam',
            name='room',
            field=models.CharField(blank=True, help_text='검사가 진행되는 상세 호실 (예: 101호)', max_length=100, null=True, verbose_name='호실명'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['building', 'floor', 'room'], name='exams_buildin_9b27e8_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['category'], name='exams_categor_f7eb60_idx'),
        ),
    ]
