# Generated by Django 5.2.4 on 2025-07-27 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_exam_building_exam_category_exam_floor_exam_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampreparation',
            name='type',
            field=models.CharField(choices=[('general', '일반 준비'), ('fasting', '금식'), ('medication', '약물 관련'), ('bladder', '방광 관련'), ('dress_code', '복장'), ('documents', '서류'), ('other', '기타')], default='general', help_text='예: 금식, 약물, 복장 등 준비사항의 종류', max_length=50, verbose_name='준비사항 타입'),
        ),
        migrations.AddIndex(
            model_name='exampreparation',
            index=models.Index(fields=['exam', 'type'], name='exam_prepar_exam_id_473f95_idx'),
        ),
    ]
