# Generated by Django 5.2.4 on 2025-08-02 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_exampreparation_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='duration',
        ),
        migrations.AddField(
            model_name='exam',
            name='average_duration',
            field=models.IntegerField(default=30, help_text='실제 검사 데이터 기반의 평균 소요 시간 (분 단위)', verbose_name='평균 소요 시간'),
        ),
        migrations.AddField(
            model_name='exam',
            name='buffer_time',
            field=models.IntegerField(default=5, help_text='검사 준비, 환자 이동 등을 위한 추가 시간 (분 단위)', verbose_name='버퍼 시간'),
        ),
    ]
