# Generated by Django 5.2.4 on 2025-08-04 12:27

from django.db import migrations

def create_initial_exam_data(apps, schema_editor):
    Exam = apps.get_model('appointments', 'Exam')
    if not Exam.objects.filter(exam_id='basic_checkup').exists():
        Exam.objects.create(
            exam_id='basic_checkup',
            title='기본 검사',
            description='기본 건강 검진',
            department='가정의학과'
        )

class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0005_remove_exam_duration_exam_average_duration_and_more"),
    ]

    operations = [
        migrations.RunPython(create_initial_exam_data),
    ]
