# Generated by Django 5.2.4 on 2025-08-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0006_add_initial_exam_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="x_coord",
            field=models.FloatField(
                default=0.0, help_text="지도상의 X 좌표값", verbose_name="X 좌표"
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="y_coord",
            field=models.FloatField(
                default=0.0, help_text="지도상의 Y 좌표값", verbose_name="Y 좌표"
            ),
        ),
        migrations.AlterField(
            model_name="exampreparation",
            name="type",
            field=models.CharField(
                choices=[
                    ("general", "일반 준비"),
                    ("fasting", "금식"),
                    ("medication", "약물 관련"),
                    ("bladder", "방광 관련"),
                    ("clothing", "복장"),
                    ("documents", "서류"),
                    ("arrival", "도착"),
                    ("other", "기타"),
                ],
                default="general",
                help_text="예: 금식, 약물, 복장 등 준비사항의 종류",
                max_length=50,
                verbose_name="준비사항 타입",
            ),
        ),
    ]
