# Generated by Django 5.2.4 on 2025-08-17 07:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_exam_x_coord_exam_y_coord_alter_exampreparation_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('result_id', models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False, verbose_name='결과 ID')),
                ('summary', models.TextField(help_text='환자가 이해하기 쉬운 검사 결과 요약', verbose_name='결과 요약')),
                ('result_pdf_url', models.URLField(blank=True, help_text='상세 검사 결과 PDF 파일 URL', max_length=500, null=True, verbose_name='상세 결과지 PDF 링크')),
                ('doctor_notes', models.TextField(blank=True, help_text='담당 의사의 추가 소견', null=True, verbose_name='의사 소견')),
                ('is_normal', models.BooleanField(default=True, help_text='검사 결과 정상 여부', verbose_name='정상 여부')),
                ('requires_followup', models.BooleanField(default=False, help_text='추가 검사나 진료가 필요한지 여부', verbose_name='추가 검사 필요')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='결과 생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='결과 수정일시')),
                ('appointment', models.OneToOneField(db_column='appointment_id', on_delete=django.db.models.deletion.CASCADE, related_name='result', to='appointments.appointment', verbose_name='예약')),
                ('created_by', models.ForeignKey(help_text='검사 결과를 입력한 의료진', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exam_results', to=settings.AUTH_USER_MODEL, verbose_name='결과 작성자')),
            ],
            options={
                'verbose_name': '검사 결과',
                'verbose_name_plural': '검사 결과 목록',
                'db_table': 'exam_results',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['appointment'], name='exam_result_appoint_f6f62d_idx'), models.Index(fields=['created_at'], name='exam_result_created_c2ac82_idx'), models.Index(fields=['is_normal', 'requires_followup'], name='exam_result_is_norm_97ea1e_idx')],
            },
        ),
    ]
