# Generated by Django 5.2.4 on 2025-08-21 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0008_examresult"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamPostCareInstruction",
            fields=[
                (
                    "instruction_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="주의사항 ID"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("general", "일반 주의사항"),
                            ("medication", "약물 복용"),
                            ("diet", "식이 주의사항"),
                            ("activity", "활동 제한"),
                            ("symptoms", "증상 관찰"),
                            ("followup", "추후 관리"),
                            ("side_effects", "부작용 관찰"),
                            ("wound_care", "상처 관리"),
                            ("hydration", "수분 섭취"),
                            ("rest", "휴식"),
                            ("other", "기타"),
                        ],
                        default="general",
                        help_text="예: 약물 복용, 식이 주의사항, 활동 제한 등",
                        max_length=50,
                        verbose_name="주의사항 타입",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="예: 처방 약물 복용법, 검사 후 수분 섭취",
                        max_length=200,
                        verbose_name="주의사항 제목",
                    ),
                ),
                ("description", models.TextField(verbose_name="상세 설명")),
                (
                    "priority",
                    models.CharField(
                        choices=[("high", "중요"), ("medium", "보통"), ("low", "일반")],
                        default="medium",
                        help_text="환자에게 강조해야 할 중요도",
                        max_length=10,
                        verbose_name="우선순위",
                    ),
                ),
                (
                    "duration_hours",
                    models.IntegerField(
                        blank=True,
                        help_text="주의사항을 지켜야 하는 시간 (예: 24시간, 48시간). null이면 기간 제한 없음",
                        null=True,
                        verbose_name="주의 기간 (시간)",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="주의사항을 나타내는 아이콘 (예: 💊, 🚫, ⚠️)",
                        max_length=200,
                        null=True,
                        verbose_name="아이콘",
                    ),
                ),
                (
                    "is_critical",
                    models.BooleanField(
                        default=False,
                        help_text="응급실 방문이 필요할 수 있는 중요한 주의사항인지 여부",
                        verbose_name="응급 주의사항",
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        db_column="exam_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_care_instructions",
                        to="appointments.exam",
                        verbose_name="검사",
                    ),
                ),
            ],
            options={
                "verbose_name": "검사 후 주의사항",
                "verbose_name_plural": "검사 후 주의사항 목록",
                "db_table": "exam_post_care_instructions",
                "ordering": ["exam", "-priority", "title"],
                "indexes": [
                    models.Index(
                        fields=["exam", "priority"],
                        name="exam_post_c_exam_id_5ee7f1_idx",
                    ),
                    models.Index(
                        fields=["exam", "type"], name="exam_post_c_exam_id_afe2d0_idx"
                    ),
                    models.Index(
                        fields=["is_critical"], name="exam_post_c_is_crit_488882_idx"
                    ),
                ],
            },
        ),
    ]
