# Generated by Django 5.2.4 on 2025-09-03 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0009_exampostcareinstruction"),
        ("nfc", "0004_facilityroute"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="exam",
            name="exams_buildin_9b27e8_idx",
        ),
        migrations.RemoveField(
            model_name="exam",
            name="building",
        ),
        migrations.RemoveField(
            model_name="exam",
            name="floor",
        ),
        migrations.RemoveField(
            model_name="exam",
            name="room",
        ),
        migrations.RemoveField(
            model_name="exam",
            name="x_coord",
        ),
        migrations.RemoveField(
            model_name="exam",
            name="y_coord",
        ),
        migrations.AddField(
            model_name="exam",
            name="location_tag",
            field=models.ForeignKey(
                blank=True,
                help_text="검사실 위치의 NFC 태그",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="exam_locations",
                to="nfc.nfctag",
                verbose_name="위치 태그",
            ),
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(
                fields=["location_tag"], name="exams_locatio_242ae8_idx"
            ),
        ),
    ]
