# Generated by Django 5.2.4 on 2025-09-19 07:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0011_unify_appointment_status_to_in_progress"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="base_price",
            field=models.DecimalField(
                decimal_places=0,
                default=25000,
                help_text="검사의 기본 수가 (원)",
                max_digits=10,
                verbose_name="기본 가격",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="insurance_coverage",
            field=models.DecimalField(
                decimal_places=2,
                default=0.7,
                help_text="0.0 ~ 1.0 사이 값 (예: 0.7 = 70%)",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
                verbose_name="보험 적용률",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "예정"),
                    ("waiting", "대기중"),
                    ("in_progress", "진행중"),
                    ("completed", "완료"),
                    ("cancelled", "취소"),
                    ("delayed", "지연"),
                ],
                default="waiting",
                max_length=20,
                verbose_name="상태",
            ),
        ),
    ]
