# Generated by Django 5.2.4 on 2025-07-24 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pw_hash',
        ),
    ]
