# Generated by Django 5.2.4 on 2025-08-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("authentication", "0002_remove_user_pw_hash"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="user",
            name="users_phoneNu_e84f73_idx",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="users_patient_c29c59_idx",
        ),
        migrations.RenameField(
            model_name="devicetoken",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="birthDate",
            new_name="birth_date",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="emergencyContact",
            new_name="emergency_contact",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="lastLoginAt",
            new_name="last_login_at",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="patientId",
            new_name="patient_id",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="phoneNumber",
            new_name="phone_number",
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["phone_number"], name="users_phone_n_a3b1c5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["patient_id"], name="users_patient_96e1c9_idx"),
        ),
    ]
