# Generated by Django 5.2.4 on 2025-08-18 03:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital_navigation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DepartmentZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="지도에 표시될 진료과/시설의 이름",
                        max_length=100,
                        unique=True,
                        verbose_name="진료과/시설 이름",
                    ),
                ),
                (
                    "svg_id",
                    models.CharField(
                        help_text="SVG 지도 내 해당 존(Zone)의 <g> 태그 ID",
                        max_length=100,
                        unique=True,
                        verbose_name="SVG 요소 ID",
                    ),
                ),
                (
                    "building",
                    models.CharField(
                        default="본관",
                        help_text="건물명 (예: 본관, 암센터)",
                        max_length=50,
                        verbose_name="건물명",
                    ),
                ),
                (
                    "floor",
                    models.CharField(
                        default="1F",
                        help_text="층수 (예: 1F, 2F)",
                        max_length=50,
                        verbose_name="층수",
                    ),
                ),
                (
                    "map_url",
                    models.CharField(
                        help_text="해당 존이 그려진 SVG 지도의 URL",
                        max_length=255,
                        verbose_name="지도 파일 경로",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="간단한 위치 설명 (예: 본관 1층 엘리베이터 옆)",
                        verbose_name="위치 설명",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="UI에 표시될 아이콘 (예: 🏥, 💊)",
                        max_length=50,
                        verbose_name="아이콘",
                    ),
                ),
                (
                    "zone_type",
                    models.CharField(
                        choices=[("DEPARTMENT", "진료과"), ("FACILITY", "편의/행정시설")],
                        default="DEPARTMENT",
                        max_length=20,
                        verbose_name="구역 타입",
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0, help_text="낮은 숫자일수록 먼저 표시", verbose_name="표시 순서"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성 상태")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "진료과/시설 존",
                "verbose_name_plural": "진료과/시설 존 목록",
                "db_table": "department_zones",
                "ordering": ["display_order", "name"],
                "indexes": [
                    models.Index(
                        fields=["zone_type", "is_active"],
                        name="department__zone_ty_1bb21c_idx",
                    ),
                    models.Index(
                        fields=["building", "floor"],
                        name="department__buildin_ee6b4b_idx",
                    ),
                    models.Index(
                        fields=["display_order"], name="department__display_53b1bc_idx"
                    ),
                ],
            },
        ),
    ]
