# Generated by Django 5.2.4 on 2025-09-03 05:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hospital_navigation", "0002_departmentzone"),
        ("nfc", "0004_facilityroute"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacilityRouteProxy",
            fields=[],
            options={
                "verbose_name": "시설 경로 (MapEditor)",
                "verbose_name_plural": "시설 경로 목록 (MapEditor)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("nfc.facilityroute",),
        ),
    ]
