# Generated by Django 5.2.4 on 2025-07-27 07:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0004_exampreparation_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NFCTag',
            fields=[
                ('tag_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='태그 ID')),
                ('tag_uid', models.CharField(help_text='NFC 하드웨어 고유 식별자', max_length=255, unique=True, verbose_name='NFC 태그 UID')),
                ('code', models.CharField(help_text='병원에서 정의한 태그 식별 코드 (고유 식별)', max_length=100, unique=True, verbose_name='태그 코드')),
                ('building', models.CharField(help_text='예: 본관, 별관, 외래동 등', max_length=100, verbose_name='건물명')),
                ('floor', models.IntegerField(verbose_name='층수')),
                ('room', models.CharField(help_text='예: 304호', max_length=100, verbose_name='호실')),
                ('description', models.TextField(help_text='태그 위치 상세 설명', verbose_name='설명')),
                ('x_coord', models.FloatField(help_text='지도상의 X 좌표값', verbose_name='X 좌표')),
                ('y_coord', models.FloatField(help_text='지도상의 Y 좌표값', verbose_name='Y 좌표')),
                ('is_active', models.BooleanField(default=True, help_text='태그 활성 상태', verbose_name='활성 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True, verbose_name='마지막 스캔 시간')),
            ],
            options={
                'verbose_name': 'NFC 태그',
                'verbose_name_plural': 'NFC 태그 목록',
                'db_table': 'nfc_tags',
                'ordering': ['building', 'floor', 'room'],
                'indexes': [models.Index(fields=['tag_uid'], name='nfc_tags_tag_uid_9adf71_idx'), models.Index(fields=['code'], name='nfc_tags_code_017718_idx'), models.Index(fields=['building', 'floor'], name='nfc_tags_buildin_b0674f_idx'), models.Index(fields=['is_active'], name='nfc_tags_is_acti_fa2d8a_idx')],
            },
        ),
        migrations.CreateModel(
            name='NFCTagExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(help_text='예: X-ray, CT, MRI', max_length=100, verbose_name='검사명')),
                ('exam_room', models.CharField(help_text='예: X-ray실 1번', max_length=100, verbose_name='검사실')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('exam', models.ForeignKey(blank=True, db_column='exam_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nfc_tag_associations', to='appointments.exam', verbose_name='검사')),
                ('tag', models.ForeignKey(db_column='tag_id', on_delete=django.db.models.deletion.CASCADE, related_name='exam_associations', to='nfc.nfctag', verbose_name='NFC 태그')),
            ],
            options={
                'verbose_name': 'NFC 태그-검사 연결',
                'verbose_name_plural': 'NFC 태그-검사 연결 목록',
                'db_table': 'nfc_tag_exams',
                'indexes': [models.Index(fields=['exam'], name='nfc_tag_exa_exam_id_60f10a_idx'), models.Index(fields=['is_active'], name='nfc_tag_exa_is_acti_5d8225_idx')],
                'unique_together': {('tag', 'exam')},
            },
        ),
        migrations.CreateModel(
            name='TagLog',
            fields=[
                ('log_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='로그 ID')),
                ('action_type', models.CharField(choices=[('scan', '위치 스캔'), ('enter', '검사실 입장'), ('exit', '검사실 퇴장'), ('fail', '스캔 실패')], default='scan', max_length=10, verbose_name='액션 유형')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='ISO 8601 형식', verbose_name='스캔 시간')),
                ('tag', models.ForeignKey(db_column='tag_id', on_delete=django.db.models.deletion.CASCADE, related_name='scan_logs', to='nfc.nfctag', verbose_name='NFC 태그')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='nfc_logs', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': 'NFC 스캔 로그',
                'verbose_name_plural': 'NFC 스캔 로그 목록',
                'db_table': 'tag_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='tag_logs_user_id_cf33d7_idx'), models.Index(fields=['tag', 'timestamp'], name='tag_logs_tag_id_48e147_idx'), models.Index(fields=['action_type'], name='tag_logs_action__104e61_idx'), models.Index(fields=['timestamp'], name='tag_logs_timesta_efc753_idx')],
            },
        ),
    ]
