# Generated by Django 5.2.4 on 2025-08-05 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfctag',
            name='x_coord',
            field=models.FloatField(default=0.0, help_text='지도상의 X 좌표값', verbose_name='X 좌표'),
        ),
        migrations.AlterField(
            model_name='nfctag',
            name='y_coord',
            field=models.FloatField(default=0.0, help_text='지도상의 Y 좌표값', verbose_name='Y 좌표'),
        ),
    ]
