# Generated by Django 5.2.4 on 2025-08-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nfc", "0002_alter_nfctag_x_coord_alter_nfctag_y_coord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nfctag",
            name="tag_uid",
            field=models.CharField(
                help_text="NFC 하드웨어 고유 식별자(NFC 태그 하드웨어 코드)",
                max_length=255,
                unique=True,
                verbose_name="NFC 태그 UID",
            ),
        ),
    ]
