# Generated by Django 4.2.7 on 2025-07-19 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('queue_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='대기열 ID')),
                ('state', models.CharField(choices=[('waiting', '대기중'), ('called', '호출됨'), ('in_progress', '진행중'), ('completed', '완료됨'), ('cancelled', '취소됨')], default='waiting', max_length=20, verbose_name='대기열 상태')),
                ('queue_number', models.IntegerField(verbose_name='대기 순번')),
                ('estimated_wait_time', models.IntegerField(help_text='분 단위', verbose_name='예상 대기 시간')),
                ('priority', models.CharField(choices=[('normal', '일반'), ('urgent', '긴급'), ('emergency', '응급')], default='normal', max_length=10, verbose_name='우선 순위 구분')),
                ('called_at', models.DateTimeField(blank=True, null=True, verbose_name='호출 시간')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='대기열 등록 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='대기열 상태 변경 시간')),
                ('appointment', models.ForeignKey(db_column='appointment_id', on_delete=django.db.models.deletion.CASCADE, related_name='queues', to='appointments.appointment', verbose_name='예약')),
                ('exam', models.ForeignKey(db_column='exam_id', on_delete=django.db.models.deletion.CASCADE, related_name='queues', to='appointments.exam', verbose_name='검사')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='queues', to=settings.AUTH_USER_MODEL, verbose_name='환자')),
            ],
            options={
                'verbose_name': '대기열',
                'verbose_name_plural': '대기열 목록',
                'db_table': 'queues',
                'ordering': ['priority', 'queue_number'],
            },
        ),
        migrations.CreateModel(
            name='QueueStatusLog',
            fields=[
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='로그 ID')),
                ('previous_state', models.CharField(max_length=20, verbose_name='이전 상태')),
                ('new_state', models.CharField(max_length=20, verbose_name='새 상태')),
                ('previous_number', models.IntegerField(blank=True, null=True, verbose_name='이전 대기번호')),
                ('new_number', models.IntegerField(blank=True, null=True, verbose_name='새 대기번호')),
                ('reason', models.CharField(blank=True, max_length=200, null=True, verbose_name='변경 사유')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='변경 시간')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_changes', to=settings.AUTH_USER_MODEL, verbose_name='변경자')),
                ('queue', models.ForeignKey(db_column='queue_id', on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='p_queue.queue', verbose_name='대기열')),
            ],
            options={
                'verbose_name': '대기열 상태 로그',
                'verbose_name_plural': '대기열 상태 로그 목록',
                'db_table': 'queue_status_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['queue', 'created_at'], name='queue_statu_queue_i_1a0e94_idx'), models.Index(fields=['new_state'], name='queue_statu_new_sta_f4bd56_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='queue',
            index=models.Index(fields=['exam', 'state'], name='queues_exam_id_eb605e_idx'),
        ),
        migrations.AddIndex(
            model_name='queue',
            index=models.Index(fields=['user'], name='queues_user_id_ccbcdb_idx'),
        ),
        migrations.AddIndex(
            model_name='queue',
            index=models.Index(fields=['state', 'queue_number'], name='queues_state_288652_idx'),
        ),
        migrations.AddIndex(
            model_name='queue',
            index=models.Index(fields=['created_at'], name='queues_created_3277e5_idx'),
        ),
        migrations.AddIndex(
            model_name='queue',
            index=models.Index(fields=['priority', 'state'], name='queues_priorit_75cf5b_idx'),
        ),
    ]
