# Generated by Django 5.2.4 on 2025-08-01 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_queue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='estimated_wait_time',
            field=models.IntegerField(default=0, help_text='분 단위', verbose_name='예상 대기 시간'),
        ),
    ]
