# Generated by Django 5.2.4 on 2025-08-01 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_queue', '0002_alter_queue_estimated_wait_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queuestatuslog',
            name='previous_state',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='이전 상태'),
        ),
    ]
