# Generated by Django 5.2.4 on 2025-08-07 06:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("p_queue", "0003_alter_queuestatuslog_previous_state"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailySchedule",
            fields=[
                (
                    "schedule_id",
                    models.CharField(
                        default=uuid.uuid4,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("schedule_date", models.DateField()),
                ("exam_id", models.CharField(max_length=50)),
                ("sequence_order", models.IntegerField()),
                (
                    "emr_appointment_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "emr_status_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "emr_department",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "emr_doctor_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "emr_room_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("emr_last_sync", models.DateTimeField(blank=True, null=True)),
                (
                    "our_queue_status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("waiting", "Waiting"),
                            ("called", "Called"),
                            ("ongoing", "Ongoing"),
                            ("completed", "Completed"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("estimated_start_time", models.TimeField(blank=True, null=True)),
                ("actual_start_time", models.DateTimeField(blank=True, null=True)),
                ("actual_end_time", models.DateTimeField(blank=True, null=True)),
                ("result_ready_time", models.DateTimeField(blank=True, null=True)),
                (
                    "result_location",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "daily_schedules",
                "ordering": ["schedule_date", "sequence_order"],
                "indexes": [
                    models.Index(
                        fields=["user", "schedule_date"],
                        name="daily_sched_user_id_63ce06_idx",
                    ),
                    models.Index(
                        fields=["schedule_date", "sequence_order"],
                        name="daily_sched_schedul_83d20c_idx",
                    ),
                    models.Index(
                        fields=["emr_appointment_id"],
                        name="daily_sched_emr_app_d6f14a_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PatientState",
            fields=[
                (
                    "state_id",
                    models.CharField(
                        default=uuid.uuid4,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "current_state",
                    models.CharField(
                        choices=[
                            ("UNREGISTERED", "Unregistered"),
                            ("ARRIVED", "Arrived"),
                            ("REGISTERED", "Registered"),
                            ("WAITING", "Waiting"),
                            ("CALLED", "Called"),
                            ("ONGOING", "Ongoing"),
                            ("COMPLETED", "Completed"),
                            ("PAYMENT", "Payment"),
                            ("FINISHED", "Finished"),
                        ],
                        default="UNREGISTERED",
                        max_length=20,
                    ),
                ),
                (
                    "current_location",
                    models.CharField(blank=True, max_length=36, null=True),
                ),
                (
                    "current_exam",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "emr_patient_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "emr_raw_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "emr_department",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("emr_appointment_time", models.DateTimeField(blank=True, null=True)),
                ("emr_latest_update", models.DateTimeField(blank=True, null=True)),
                ("is_logged_in", models.BooleanField(default=False)),
                (
                    "login_method",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_state",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "patient_states",
                "indexes": [
                    models.Index(
                        fields=["current_state"], name="patient_sta_current_a968e4_idx"
                    ),
                    models.Index(
                        fields=["emr_patient_id"], name="patient_sta_emr_pat_9b31c8_idx"
                    ),
                    models.Index(
                        fields=["emr_appointment_time"],
                        name="patient_sta_emr_app_c28ecb_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StateTransition",
            fields=[
                (
                    "transition_id",
                    models.CharField(
                        default=uuid.uuid4,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "from_state",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("UNREGISTERED", "Unregistered"),
                            ("ARRIVED", "Arrived"),
                            ("REGISTERED", "Registered"),
                            ("WAITING", "Waiting"),
                            ("CALLED", "Called"),
                            ("ONGOING", "Ongoing"),
                            ("COMPLETED", "Completed"),
                            ("PAYMENT", "Payment"),
                            ("FINISHED", "Finished"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "to_state",
                    models.CharField(
                        choices=[
                            ("UNREGISTERED", "Unregistered"),
                            ("ARRIVED", "Arrived"),
                            ("REGISTERED", "Registered"),
                            ("WAITING", "Waiting"),
                            ("CALLED", "Called"),
                            ("ONGOING", "Ongoing"),
                            ("COMPLETED", "Completed"),
                            ("PAYMENT", "Payment"),
                            ("FINISHED", "Finished"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("emr_sync", "EMR Sync"),
                            ("nfc_tag", "NFC Tag"),
                            ("system_auto", "System Auto"),
                            ("nurse_manual", "Nurse Manual"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "trigger_source",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "location_at_transition",
                    models.CharField(blank=True, max_length=36, null=True),
                ),
                ("exam_id", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "emr_reference",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "emr_status_before",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "emr_status_after",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="state_transitions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "state_transitions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="state_trans_user_id_835b0b_idx",
                    ),
                    models.Index(
                        fields=["trigger_type", "created_at"],
                        name="state_trans_trigger_fd1f45_idx",
                    ),
                    models.Index(
                        fields=["from_state", "to_state"],
                        name="state_trans_from_st_00880a_idx",
                    ),
                ],
            },
        ),
    ]
