# Generated by Django 5.2.4 on 2025-08-07 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("p_queue", "0004_dailyschedule_patientstate_statetransition"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="queue",
            name="schedule",
            field=models.ForeignKey(
                blank=True,
                db_column="schedule_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_queues",
                to="p_queue.dailyschedule",
                verbose_name="일일 스케줄 연결",
            ),
        ),
        migrations.AddField(
            model_name="queuestatuslog",
            name="estimated_wait_time_at_time",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="변경 시점 예상대기시간"
            ),
        ),
        migrations.AddField(
            model_name="queuestatuslog",
            name="location",
            field=models.CharField(
                blank=True, max_length=36, null=True, verbose_name="변경 시점 위치"
            ),
        ),
        migrations.AddField(
            model_name="queuestatuslog",
            name="metadata",
            field=models.JSONField(blank=True, null=True, verbose_name="추가 컨텍스트 정보"),
        ),
        migrations.AddField(
            model_name="queuestatuslog",
            name="queue_position_at_time",
            field=models.IntegerField(blank=True, null=True, verbose_name="변경 시점 대기순서"),
        ),
        migrations.AddIndex(
            model_name="queuestatuslog",
            index=models.Index(
                fields=["location"], name="queue_statu_locatio_4ff469_idx"
            ),
        ),
    ]
