# Generated by Django 5.2.4 on 2025-08-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("p_queue", "0005_queue_schedule_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queue",
            name="state",
            field=models.CharField(
                choices=[
                    ("waiting", "대기중"),
                    ("called", "호출됨"),
                    ("ongoing", "진행중(검사실/진료실 입장)"),
                    ("completed", "완료"),
                    ("delayed", "지연"),
                    ("no_show", "미방문/이탈 (No-Show)"),
                    ("cancelled", "취소"),
                ],
                default="waiting",
                max_length=20,
                verbose_name="대기열 상태",
            ),
        ),
    ]
