# Generated by Django 5.2.4 on 2025-08-15 07:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("p_queue", "0006_alter_queue_state"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="queue",
            name="schedule",
        ),
        migrations.DeleteModel(
            name="DailySchedule",
        ),
    ]
