# Generated by Django 5.2.4 on 2025-08-15 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0007_exam_x_coord_exam_y_coord_alter_exampreparation_type"),
        ("p_queue", "0007_remove_queue_schedule_delete_dailyschedule"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientstate",
            name="current_exam",
            field=models.ForeignKey(
                blank=True,
                db_column="current_exam_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="patient_states",
                to="appointments.exam",
                verbose_name="현재 검사",
            ),
        ),
        migrations.AddIndex(
            model_name="patientstate",
            index=models.Index(
                fields=["current_exam"], name="patient_sta_current_046bb6_idx"
            ),
        ),
    ]
