# Generated by Django 5.2.4 on 2025-08-24 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("p_queue", "0008_alter_patientstate_current_exam_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="queuestatuslog",
            name="changed_by",
            field=models.ForeignKey(
                blank=True,
                db_column="changed_by_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="queue_changes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="변경자",
            ),
        ),
    ]
