# Generated by Django 5.2.4 on 2025-09-03 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nfc", "0004_facilityroute"),
        ("p_queue", "0009_alter_queuestatuslog_changed_by"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="queuestatuslog",
            new_name="queue_statu_locatio_8c5264_idx",
            old_name="queue_statu_locatio_4ff469_idx",
        ),
        migrations.AlterField(
            model_name="patientstate",
            name="current_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_patients",
                to="nfc.nfctag",
            ),
        ),
        migrations.AlterField(
            model_name="queuestatuslog",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="nfc.nfctag",
                verbose_name="변경 시점 위치",
            ),
        ),
        migrations.AlterField(
            model_name="statetransition",
            name="location_at_transition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="nfc.nfctag",
            ),
        ),
    ]
