# Generated by Django 5.2.4 on 2025-09-06 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_queue', '0010_rename_queue_statu_locatio_4ff469_idx_queue_statu_locatio_8c5264_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientstate',
            name='current_state',
            field=models.CharField(choices=[('UNREGISTERED', 'UNREGISTERED'), ('ARRIVED', 'ARRIVED'), ('REGISTERED', 'REGISTERED'), ('WAITING', 'WAITING'), ('CALLED', 'CALLED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('PAYMENT', 'PAYMENT'), ('FINISHED', 'FINISHED')], default='UNREGISTERED', max_length=20),
        ),
        migrations.AlterField(
            model_name='queue',
            name='state',
            field=models.CharField(choices=[('waiting', 'waiting'), ('delayed', 'delayed'), ('called', 'called'), ('no_show', 'no_show'), ('in_progress', 'in_progress'), ('completed', 'completed'), ('cancelled', 'cancelled')], default='waiting', max_length=20, verbose_name='대기열 상태'),
        ),
        migrations.AlterField(
            model_name='statetransition',
            name='from_state',
            field=models.CharField(blank=True, choices=[('UNREGISTERED', 'UNREGISTERED'), ('ARRIVED', 'ARRIVED'), ('REGISTERED', 'REGISTERED'), ('WAITING', 'WAITING'), ('CALLED', 'CALLED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('PAYMENT', 'PAYMENT'), ('FINISHED', 'FINISHED')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='statetransition',
            name='to_state',
            field=models.CharField(choices=[('UNREGISTERED', 'UNREGISTERED'), ('ARRIVED', 'ARRIVED'), ('REGISTERED', 'REGISTERED'), ('WAITING', 'WAITING'), ('CALLED', 'CALLED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('PAYMENT', 'PAYMENT'), ('FINISHED', 'FINISHED')], max_length=20),
        ),
    ]
