# Generated by Django 5.2.4 on 2025-09-29 01:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("p_queue", "0012_unify_state_to_in_progress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientstate",
            name="current_state",
            field=models.CharField(
                choices=[
                    ("UNREGISTERED", "UNREGISTERED"),
                    ("ARRIVED", "ARRIVED"),
                    ("REGISTERED", "REGISTERED"),
                    ("WAITING", "WAITING"),
                    ("CALLED", "CALLED"),
                    ("IN_PROGRESS", "IN_PROGRESS"),
                    ("COMPLETED", "COMPLETED"),
                    ("PAYMENT", "PAYMENT"),
                    ("FINISHED", "FINISHED"),
                ],
                default="UNREGISTERED",
                max_length=20,
                verbose_name="현재 상태",
            ),
        ),
        migrations.AlterField(
            model_name="queue",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="대기열 등록 시간"
            ),
        ),
        migrations.AlterField(
            model_name="queue",
            name="updated_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="대기열 상태 변경 시간"
            ),
        ),
    ]
