# Generated by Django 5.2.4 on 2025-10-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("p_queue", "0013_alter_patientstate_current_state_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientstate",
            name="current_state",
            field=models.CharField(
                choices=[
                    ("UNREGISTERED", "UNREGISTERED"),
                    ("ARRIVED", "ARRIVED"),
                    ("REGISTERED", "REGISTERED"),
                    ("WAITING", "WAITING"),
                    ("CALLED", "CALLED"),
                    ("IN_PROGRESS", "IN_PROGRESS"),
                    ("PAYMENT", "PAYMENT"),
                    ("FINISHED", "FINISHED"),
                ],
                default="UNREGISTERED",
                max_length=20,
                verbose_name="현재 상태",
            ),
        ),
        migrations.AlterField(
            model_name="statetransition",
            name="from_state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("UNREGISTERED", "UNREGISTERED"),
                    ("ARRIVED", "ARRIVED"),
                    ("REGISTERED", "REGISTERED"),
                    ("WAITING", "WAITING"),
                    ("CALLED", "CALLED"),
                    ("IN_PROGRESS", "IN_PROGRESS"),
                    ("PAYMENT", "PAYMENT"),
                    ("FINISHED", "FINISHED"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="statetransition",
            name="to_state",
            field=models.CharField(
                choices=[
                    ("UNREGISTERED", "UNREGISTERED"),
                    ("ARRIVED", "ARRIVED"),
                    ("REGISTERED", "REGISTERED"),
                    ("WAITING", "WAITING"),
                    ("CALLED", "CALLED"),
                    ("IN_PROGRESS", "IN_PROGRESS"),
                    ("PAYMENT", "PAYMENT"),
                    ("FINISHED", "FINISHED"),
                ],
                max_length=20,
            ),
        ),
    ]
